site: Scratch Paper
url: "https://ashwinreddy.github.io" #yoururl
title: Scratch Paper
description: Simple and minimalistic jekyll blogging theme.
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: Ashwin Reddy #yourusername
  avatar:
  email: adreddy@berkeley.edu #youremail
  url: #yoururl
permalink: pretty

baseurl: "/blog"

highlighter: rouge 

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
